exports.allmodes = [{
    filename: ".json",
    mode: "javascript",
    modeName: "Javascript(JSON)"
}, {
    filename: ".css",
    mode: "CSS",
    modeName: "CSS"
}, {
    filename: "js",
    mode: "javascript",
    modeName: "Javascript"
}, {
    filename: ".html",
    mode: "html",
    modeName: "HTML"
}, {
    filename: ".rb",
    mode: "ruby",
    modeName: "Ruby"
}, {
    filename: ".py",
    mode: "python",
    modeName: "Python"
}, {
    filename: ".c",
    mode: "c",
    modeName: "C"
}, {
    filename: ".cpp",
    mode: "cpp",
    modeName: "C++"
}, {
    filename: ".java",
    mode: "java",
    modeName: "Java"
}, {
    filename: ".cl",
    mode: "commonlisp",
    modeName: "Common Lisp"
}, {
    filename: ".php",
    mode: "php",
    modeName: "PHP"
}, {
    filename: ".md",
    mode: "markdown",
    modeName: "Markdown"
}];
